In [20]:
from sklearn.datasets import load_iris
import tensorflow as tf
import numpy as np

In [21]:
iris = load_iris()

In [22]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [23]:
X = iris['data']

In [24]:
y = iris['target']

In [25]:
y.dtype

dtype('int32')

In [26]:
from sklearn.cross_validation import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [28]:
import tensorflow.contrib.learn as learn

In [29]:
feature_columns = [tf.contrib.layers.real_valued_column("", dimension=4)]

In [31]:
classifier = learn.DNNClassifier(hidden_units=[10,20,10],n_classes=3,feature_columns=feature_columns)

Instructions for updating:
Please switch to tf.contrib.estimator.*_head.
Instructions for updating:
Please replace uses of any Estimator from tf.contrib.learn with an Estimator from tf.estimator.*
Instructions for updating:
When switching to tf.estimator.Estimator, use tf.estimator.RunConfig instead.
INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x0000015CBDD33F60>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_train_distribute': None, '_device_fn': None, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_log_step_count_steps': 100, '_session_config': None, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_mo

In [37]:
classifier.fit(X_train,y_train,steps=2000)

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\theda\AppData\Local\Temp\tmpaaolbzv7\model.ckpt-200
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 200 into C:\Users\theda\AppData\Local\Temp\tmpaaolbzv7\model.ckpt.
INFO:tensorflow:loss = 0.17058873, step = 201
INFO:tensorflow:global_step/sec: 312.575
INFO:tensorflow:loss = 0.09531372, step = 301 (0.320 sec)
INFO:tensorflow:global_step/sec: 454.656
INFO:tensorflow:loss = 0.07720986, step = 401 (0.220 sec)
INFO:tensorflow:global_step/sec: 500.127
INFO:tensorflow:loss = 0.06839608, step = 501 (0.208 sec)
INFO:tensorflow:global_step/sec: 454.028
INFO:tensorflow:loss = 0.066666886, step = 601 (0.216 sec)
INFO:tensorflow:global_step/sec: 490.315
INFO:tensorflow:loss = 0.060048833, step = 701 (0.200 sec)
INFO:tensorflow:global_step/sec: 532.043
INFO:tensorflow:loss = 0.06008275, step = 8

DNNClassifier(params={'head': <tensorflow.contrib.learn.python.learn.estimators.head._MultiClassHead object at 0x0000015CBC21E860>, 'hidden_units': [10, 20, 10], 'feature_columns': (_RealValuedColumn(column_name='', dimension=4, default_value=None, dtype=tf.float32, normalizer=None),), 'optimizer': None, 'activation_fn': <function relu at 0x0000015CB8498598>, 'dropout': None, 'gradient_clip_norm': None, 'embedding_lr_multipliers': None, 'input_layer_min_slice_size': None})

In [38]:
accuracy_score = classifier.evaluate(X_test, y_test)["accuracy"]
print('Accuracy: {0:f}'.format(accuracy_score))

Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
INFO:tensorflow:Starting evaluation at 2018-08-31-14:27:31
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\theda\AppData\Local\Temp\tmpaaolbzv7\model.ckpt-2200
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Finished evaluation at 2018-08-31-14:27:32
INFO:tensorflow:Saving dict for global step 2200: 

In [34]:
iris_predictions

<generator object DNNClassifier.predict_classes.<locals>.<genexpr> at 0x0000015CBDDBAEB8>

In [35]:
from sklearn.metrics import classification_report,confusion_matrix

In [39]:
iris_predictions = list(classifier.predict(X_test))
print(classification_report(y_test,  iris_predictions))
print('\n')
print(confusion_matrix(y_test,  iris_predictions))
print('\n')

INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\theda\AppData\Local\Temp\tmpaaolbzv7\model.ckpt-2200
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        12
          1       1.00      1.00      1.00        17
          2       1.00      1.00      1.00        16

avg / total       1.00      1.00      1.00        45



[[12  0  0]
 [ 0 17  0]
 [ 0  0 16]]


