In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('india data PM10 classified.csv')

In [3]:
df.head()

PM 10  Max Temp  Avg Dew Point  Max Wind Speed  Avg Humidity  Max Humidity  \
0      0        96             70               9          58.5            83   
1      0       108             61              15          31.0            53   
2      0       109             69               7          34.0            49   
3      1        58             50               6          81.5            97   
4      1        71             61              14          84.0           100   

   Max Pressure  Min Pressure  Precipitation  
0         29.76         29.65           0.08  
1         29.62         29.47           0.00  
2         29.60         29.45           0.00  
3         30.11         29.96           0.00  
4         29.97         29.83           0.28

In [4]:
df.shape

(248, 9)

In [5]:
X = df.drop('PM 10',axis=1)
y = df['PM 10']

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [7]:
X_train.shape

(198, 8)

In [8]:
X_test.shape

(50, 8)

In [9]:
y_train.shape

(198,)

In [10]:
y_test.shape

(50,)

In [11]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_jobs=2, random_state=0)

In [12]:
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [13]:
predictions = clf.predict(X_test)

In [14]:
clf.predict_proba(X_test)[0:10]

array([[0. , 1. , 0. , 0. ],
       [0. , 0.1, 0.9, 0. ],
       [0. , 0.7, 0.3, 0. ],
       [0. , 0.9, 0.1, 0. ],
       [0.1, 0.9, 0. , 0. ],
       [0. , 0.9, 0.1, 0. ],
       [0. , 0.1, 0.9, 0. ],
       [0. , 1. , 0. , 0. ],
       [0. , 0.4, 0.6, 0. ],
       [0.1, 0.9, 0. , 0. ]])

In [15]:
predictions[0:5]

array([1, 2, 1, 1, 1], dtype=int64)

In [16]:
y_test[0:5]

108    2
98     2
32     1
27     1
150    1
Name: PM 10, dtype: int64

In [17]:
pd.crosstab(y_test, predictions, rownames=['Actual'], colnames=['Predicted'])

Predicted  0   1   2  3
Actual                 
0          1   0   0  0
1          0  26   0  0
2          0   5  15  0
3          0   0   1  2

In [18]:
list(zip(X_test, clf.feature_importances_))

[('Max Temp', 0.1005843430650479),
 ('Avg Dew Point', 0.1256782577309022),
 ('Max Wind Speed', 0.11185730773136437),
 ('Avg Humidity', 0.20190915455815092),
 ('Max Humidity', 0.14651748012088067),
 ('Max Pressure', 0.12784751420683932),
 ('Min Pressure', 0.1400872606822366),
 ('Precipitation', 0.045518681904578015)]

In [23]:
errors = abs(predictions - y_test)
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 94.22 %.


In [20]:
from sklearn.metrics import confusion_matrix

conf_mat = confusion_matrix(y_test, predictions)
print(conf_mat)

[[ 1  0  0  0]
 [ 0 26  0  0]
 [ 0  5 15  0]
 [ 0  0  1  2]]


In [21]:
from sklearn import metrics

print("Accuracy", metrics.accuracy_score(y_test, predictions) * 100, '%')

Accuracy 88.0 %


In [22]:
from sklearn.metrics import classification_report

print(classification_report(y_test,predictions))  

             precision    recall  f1-score   support

          0       1.00      1.00      1.00         1
          1       0.84      1.00      0.91        26
          2       0.94      0.75      0.83        20
          3       1.00      0.67      0.80         3

avg / total       0.89      0.88      0.88        50

