In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('india data PM10 classified.csv')

In [4]:
df.head()

PM 10  Max Temp  Avg Dew Point  Max Wind Speed  Avg Humidity  Max Humidity  \
0      0        96             70               9          58.5            83   
1      0       108             61              15          31.0            53   
2      0       109             69               7          34.0            49   
3      1        58             50               6          81.5            97   
4      1        71             61              14          84.0           100   

   Max Pressure  Min Pressure  Precipitation  
0         29.76         29.65           0.08  
1         29.62         29.47           0.00  
2         29.60         29.45           0.00  
3         30.11         29.96           0.00  
4         29.97         29.83           0.28

In [6]:
df.shape

(248, 9)

In [8]:
X = df.drop('PM 10', axis=1)
y = df['PM 10']

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [10]:
X_train.shape

(198, 8)

In [11]:
X_test.shape

(50, 8)

In [12]:
y_train.shape

(198,)

In [13]:
y_test.shape

(50,)

In [14]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='linear')  
svclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [15]:
predictions = svclassifier.predict(X_test)

In [17]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, predictions))  
print(classification_report(y_test, predictions))  

[[ 0  0  0  0]
 [ 1 26  6  0]
 [ 0 11  3  0]
 [ 0  2  1  0]]
             precision    recall  f1-score   support

          0       0.00      0.00      0.00         0
          1       0.67      0.79      0.72        33
          2       0.30      0.21      0.25        14
          3       0.00      0.00      0.00         3

avg / total       0.52      0.58      0.55        50



C:\Users\theda\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\theda\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [ ]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='poly', degree=8)  
svclassifier.fit(X_train, y_train)

In [ ]:
predictions = svclassifier.predict(X_test)  