In [1]:
%matplotlib inline               
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('data without aqi.csv')

In [3]:
df.head()

Avg PM2.5  Avg Max Temp  Avg Dew Temp  Avg Wind Speed  Avg Humidity
0   8.642857     64.857143     33.571429        9.142857     48.357143
1  36.614286     64.000000     40.000000        6.571429     60.500000
2  24.628571     77.428571     36.714286        6.428571     44.142857
3   9.300000     84.000000     27.428571        7.142857     25.571429
4  11.485714     68.142857     42.285714        7.571429     54.571429

In [4]:
df.describe()

Avg PM2.5  Avg Max Temp  Avg Dew Temp  Avg Wind Speed  Avg Humidity
count  449.000000    449.000000    449.000000      449.000000    449.000000
mean    15.151098     75.795737     49.840280        8.876869     60.937480
std      5.585026      7.451177      8.928992        2.263398      9.173827
min      5.985714     57.571429     21.571429        4.000000     25.571429
25%     10.828571     70.714286     43.571429        8.000000     54.714286
50%     14.128571     75.571429     51.000000        8.714286     62.142857
75%     18.800000     81.000000     57.428571        9.428571     67.785714
max     36.614286     95.857143     65.571429       37.857143     86.571429

In [5]:
df.shape

(449, 5)

In [6]:
X = df.drop('Avg PM2.5',axis=1)
y = np.asarray(df['Avg PM2.5'], dtype="|S6")

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
X_train.shape

(359, 4)

In [10]:
X_test.shape

(90, 4)

In [11]:
y_train.shape

(359,)

In [12]:
y_test.shape

(90,)

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()

In [15]:
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [16]:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
from sklearn.neural_network import MLPClassifier

In [18]:
mlp = MLPClassifier(hidden_layer_sizes=(4,4,4), max_iter=2000)

In [19]:
mlp.fit(X_train, y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(4, 4, 4), learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [20]:
predictions = mlp.predict(X_test)

In [21]:
from sklearn.metrics import classification_report,confusion_matrix

In [22]:
print(confusion_matrix(y_test,predictions))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [23]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

    b'10.0'       0.00      0.00      0.00         1
  b'10.014'       0.00      0.00      0.00         1
  b'10.042'       0.00      0.00      0.00         1
  b'10.142'       0.00      0.00      0.00         1
    b'10.2'       0.00      0.00      0.00         0
  b'10.271'       0.00      0.00      0.00         1
  b'10.371'       0.00      0.00      0.00         1
    b'10.4'       0.00      0.00      0.00         1
  b'10.457'       0.00      0.00      0.00         1
    b'10.5'       0.00      0.00      0.00         0
  b'10.542'       0.00      0.00      0.00         1
  b'10.671'       0.00      0.00      0.00         1
  b'10.785'       0.00      0.00      0.00         1
  b'10.828'       0.00      0.00      0.00         0
    b'10.9'       0.00      0.00      0.00         0
  b'10.914'       0.00      0.00      0.00         1
  b'11.071'       0.00      0.00      0.00         0
  b'11.228'       0.00      0.00      0.00   

C:\Users\theda\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\theda\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
